version: '3'
services:

  brc20query:
    build: .
    image: brc20query:v1.0
    volumes:
      - ./data:/data/data
    ports:
      - "5555:8000"
    restart: always
    environment:
      LISTEN: 0.0.0.0:8000
      BASE_PATH: ""
      BRC20_PROCESS_AFTER_HEIGHT: 767400
      BRC20_PROCESS_BEFORE_HEIGHT: 824478

      DB_USER: "ordinals"
      DB_HOST: "192.168.1.100"
      DB_PORT: "5432"
      DB_DATABASE: "opi"
      DB_PASSWD: "xxxxxxxxxx"

    labels:
      - "name=brc20query"
    logging:
      driver: "json-file"
      options:
        labels: "name"
        max-size: "1g"
        max-file: "3"
